apiVersion: v1
kind: Service
metadata:
  name: quote-api-service
spec:
  type: NodePort # Tarayıcımızdan erişebilmek için NodePort türünde açıyoruz
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080 # Bilgisayarımızdan http://<minikube-ip>:30080 diyerek API'ye erişebileceğiz
  selector:
    app: quote-api
